services:
  backend:
    image: lsw71311/seatea:latest
    expose:
        - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-local}
      - SPRING_DATASOURCE_URL=${DB_URL:-jdbc:mysql://db:3306/seatea?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME:-user}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:-password}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=seatea
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Seoul
    ports:
      - "3307:3306"
    volumes:
      - seatea_mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    profiles: [ "local" ]

volumes:
  seatea_mysql_data: