spring:
  application:
    name: SeaTea

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # 운영에서는 스키마 자동 변경 금지 (none 도 가능)
    show-sql: false     # 운영에서는 SQL 로그 비활성화
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: Asia/Seoul

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO
    org.springframework.web: INFO